# Path to your Oh My Zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Theme https://github.com/ohmyzsh/ohmyzsh/wiki/themes
ZSH_THEME="gnzh"

# Plugins
plugins=(git aws fzf zsh-autosuggestions zsh-syntax-highlighting)

# Oh My Zsh
source $ZSH/oh-my-zsh.sh
